"""add model and request logs

Revision ID: c1dd4cadc258
Revises: e3141bc46196
Create Date: 2026-03-25 01:54:38.587967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1dd4cadc258'
down_revision: Union[str, Sequence[str], None] = 'e3141bc46196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model_type', sa.Enum('OPENAI', 'HUGGINGFACE', 'LOCAL', 'CUSTOM_API', name='modeltype'), nullable=False),
    sa.Column('sensitivity_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='sensitivitylevel'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
